### ISSUE TITLE
Pello handling

### ISSUE THREAD

**Issue by OldShaterhan** [matkor/ecoaliface#3]
Hey,

I'd like to adjust code from here to handle Pello - I believe code is quite similar to the eCoal and Bruli, so I started debugging your code. Unfortunalely I got response from following request:
```
http://<heaterIP>/?com=0201000500020000A903
```
I got HTML as a response. 

What kind of response should be returned from the request? JSON?

Thanks in advance for help :)

**Comment by matkor** [comment]
I did not write / reverse engineer low level request parsing code. I took it from existing projects, but looks to me eCoal controllers returns encoded sequence of integers in most cases parsed via _parse_seq_of_ints(). 
I have no idea how Pello interface works. If it's web browser based, perhaps you could sniff over TCP/IP what goes in and back between www browser and controller.

**Comment by OldShaterhan** [comment]
Are you able to show the screen from the local web interface of eCoal/Bruli page? I'd like to see how similar it looks like to the Pello (available options, etc.) I believe that may show me a bit more information ;) (I have found some way of authorization and data reading, but I don't see yet how to update options).

**Comment by matkor** [comment]
![ecoal_www_iface_mainpage](https://user-images.githubusercontent.com/552570/137641268-fedc148c-c923-413d-8d97-7770cc80b61a.png)

Sorry for late response, I missed notification somehow.

**Comment by OldShaterhan** [comment]
No problem ;)
It seems that it is definitely different than eSterownik 3.5 based solutions, but tbh - schema looks definitely better (I have such preview but only on eSterownik page, not on local page).

I'll need to prepare new integration, unfortunately I'm not really in Python.

Thanks again!
