### ISSUE TITLE
ecoaliface version on pypi not updated

### ISSUE THREAD

**Issue by krz-sas** [matkor/ecoaliface#7]
The ecoaliface version on pypi is 0.5.0 and the repo already contains 0.7.0 version. Please update the version on pypi, so that it can be used in homeassistant.

  https://pypi.org/project/ecoaliface/

**Comment by matkor** [comment]
Can you, please, test if test.pypi.org 
https://test.pypi.org/project/ecoaliface/
is OK?
I will upload same version to pypi.org  then.
TIA, regards.

**Comment by krz-sas** [comment]
Ok, will test and get back to you.

**Comment by krz-sas** [comment]
Installed it in my running instance of home assistant. For now it works as previous version: 0.4.0, because there is no support for new sensor type, but I'll add it. Good news for you is that it will not be automatically updated to latest version: 0.7.0 until there is an explicit requirement in the manifest.

**Comment by matkor** [comment]
Updated on pypi.
